# Generated by Django 3.1 on 2021-01-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210113_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('TC', 'Tecnologias'), ('CR', 'Curiosidades'), ('GR', 'Geral')], default='GR', max_length=2, verbose_name='Categorias'),
        ),
    ]
