# Generated by Django 3.1 on 2021-01-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_post_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('TC', 'Tecnologias'), ('CR', 'Curiosidades'), ('GR', 'Geral')], default='GR', max_length=2, verbose_name='Categoria'),
        ),
    ]
